# Generated by Django 3.2 on 2022-01-14 18:45

from django.db import migrations, models
import memories.utils.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=memories.utils.image_utils.get_upload_path),
        ),
    ]
